// import React from "react";
// import { Link } from "react-router-dom";
// const Home = () => {
//   return (
//     <div className="dhiwise-navigation">
//       <h1>Homepage</h1>
//       <p className="headline">
//         This project was generated By{" "}
//         <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
//         to navigate through all pages.
//       </p>
//       <ul>
//         <li>
//           <Link to="/">MainDashboard</Link>
//         </li>
//         <li>
//           <Link to="/transaction">Transaction</Link>
//         </li>
//         <li>
//           <Link to="/accounts">Accounts</Link>
//         </li>
//         <li>
//           <Link to="/investments">Investments</Link>
//         </li>
//         <li>
//           <Link to="/creditcards">CreditCards</Link>
//         </li>
//         <li>
//           <Link to="/deposit">Loan</Link>
//         </li>
//         <li>
//           <Link to="/services">Services</Link>
//         </li>
//         <li>
//           <Link to="/settingeditprofile">SettingEditProfile</Link>
//         </li>
//         <li>
//           <Link to="/settingpagepreferences">SettingPagePreferences</Link>
//         </li>
//         <li>
//           <Link to="/settingpagesecurity">SettingPageSecurity</Link>
//         </li>
//       </ul>
//     </div>
//   );
// };
// export default Home;

import React from "react";
import { Link } from "react-router-dom";

const LandingPage: React.FC = () => {
  const cardContent = [
    {
      title: "Choose a Goal",
      description:
        "With the use of mykollo ID, Kollocash ensures that money set to be borrowed to a Kollo user is tracked and retrieved at the set time. You are never at a loss when a borrower does not pay at the set time. Keep calm while you loan to grow your kollo cash.",
    },
    {
      title: "Meet Expense",
      description:
        "Never go out of budget! With Kollocash, you can set expenses goals with your income. Kollocash helps users meet their targets through a flexible saving plan aligned with their income.",
    },
    {
      title: "Sell on Credit",
      description:
        "Business transactions just got easier with Kollocash. You can keep a good track of all your incoming credits or outgoing debits when you make use of Kollocash track my payments.",
    },
    {
      title: "Fund mykollo",
      description:
        "You can fundraise for a project, ask for gifts, or request for payment with the use of fundmykollo link.",
    },
  ];

  return (
    <div className="bg-gray-100  flex flex-col justify-center items-center">
      <h1 className="text-4xl font-bold mb-4">Welcome to Your Payment App</h1>
      <p className="text-lg text-gray-600 mb-8">
        Leverage on Paystack for easy money transactions.
      </p>
      <div className="flex flex-col space-x-4">
        <div className="flex justify-center items-center">
          {[
            {
              title: "Borrow Money",
              link: "/borrow",
              className:
                "bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 mr-4",
            },
            {
              title: "Send Money",
              link: "/send",
              className:
                "bg-green-500 text-white py-2 px-4 rounded-md hover:bg-green-600 mr-4",
            },
            {
              title: " Receive Money",
              link: "/receive",
              className:
                "bg-purple-500 text-white py-2 px-4 rounded-md hover:bg-purple-600 mr-4",
            },
          ].map((card, i) => (
            <Link key={i} to={card.link} className={card.className}>
              {card.title}
            </Link>
          ))}
        </div>
        <div className="space-y-4 mt-4 flex flex-wrap">
          {cardContent.map((content, index) => (
            <div
              key={index}
              className="bg-white p-4 rounded-md shadow-md w-[47%] sm:w-[47%] mt-10 mr-6 mb-8"
            >
              <h2 className="text-lg font-semibold mb-2">{content.title}</h2>
              <p className="text-gray-600">{content.description}</p>
            </div>
          ))}
        </div>

        <div className="flex items-center mt-8 w-full">
          <img
            src="https://kollo-cash.netlify.app/img/6.4204f82f.png"
            alt="App Screenshot"
            className="w-[48%] h-100 mr-4"
          />
          <div>
            <h3 className="text-lg font-semibold">
              Experience Seamless Transactions
            </h3>
            <p className="text-gray-600">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et
              feugiat libero.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;
